In [1]:
#Set the path for the main directory for the project
#This will be the only line you need to modify in the notebook. You will also have to edit perf_cols.txt under 
#sqlite folder to specify which columns you would like to import to db
dir_path = "/Users/allen/Documents/sqlite"

In [2]:
import sys
import os
#sys.path.append(os.path.abspath('../'))
os.chdir(dir_path)

import sqlite.create_fp_db as create_fp_db

print("Current directory is: %s" % (os.getcwd()))

Current directory is: /Users/allen/Documents/sqlite

In [3]:
#Defining paths for db and raw files
#db_path = 'data/processed/fp_db.sqlite'
db_path = dir_path +'/data/processed/small_db.sqlite'
#raw_path = 'data/raw/On_Time_On_Time_Performance_2015_1_v1.csv' #location of raw folder not path
#raw_folder= 'data/raw'
raw_folder = dir_path + '/data/raw'
col_path = dir_path + '/sqlite/perf_cols.txt'
#cols = ['Year','Quarter','Month','DayofMonth','DayOfWeek','FlightDate','UniqueCarrier','AirlineID','Carrier','TailNum','FlightNum']
print(db_path)

/Users/allen/Documents/sqlite/data/processed/small_db.sqlite

In [4]:
#Import list of columns based on the text file perf_cols.txt in the sqlite folder
#This will print all the columns that are used
cols_file = open(col_path)
cols = cols_file.read().split('\n')
cols_file.close()
print(cols)

['Year', 'Quarter', 'Month', 'DayofMonth', 'DayOfWeek', 'FlightDate', 'UniqueCarrier', 'AirlineID', 'Carrier', 'TailNum', 'FlightNum', 'OriginAirportID', 'OriginAirportSeqID', 'OriginCityMarketID', 'Origin', 'OriginCityName', 'OriginState', 'OriginStateFips', 'OriginStateName', 'OriginWac', 'DestAirportID', 'DestAirportSeqID', 'DestCityMarketID', 'Dest', 'DestCityName', 'DestState', 'DestStateFips', 'DestStateName', 'DestWac', 'CRSDepTime', 'DepTime', 'DepDelay', 'DepDelayMinutes', 'DepDel15', 'DepartureDelayGroups', 'DepTimeBlk', 'TaxiOut', 'WheelsOff', 'WheelsOn', 'TaxiIn', 'CRSArrTime', 'ArrTime', 'ArrDelay', 'ArrDelayMinutes', 'ArrDel15', 'ArrivalDelayGroups', 'ArrTimeBlk', 'Cancelled', 'CancellationCode', 'Diverted', 'CRSElapsedTime', 'ActualElapsedTime', 'AirTime', 'Flights', 'Distance', 'DistanceGroup', 'CarrierDelay', 'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay', 'FirstDepTime', 'TotalAddGTime', 'LongestAddGTime']

In [5]:
#Creating the db file
#Look into adding this file checker
create_fp_db.create_db(db_path)

DB created succesfully at :/Users/allen/Documents/sqlite/data/processed/small_db.sqlite

In [6]:
#Add the wanted columns to the table
db_cols = create_fp_db.col_parse(cols)
create_fp_db.create_table(db_path,db_cols)
print(db_cols)

 'YEAR' NOT NULL,'Quarter' INT NOT NULL,'Month' INT NOT NULL,'DayofMonth' INT NOT NULL,'DayOfWeek' INT NOT NULL,'FlightDate' DATE NOT NULL,'UniqueCarrier' VARCHAR(10) NULL,'AirlineID' INT NOT NULL,'Carrier' VARCHAR(10) NULL,'TailNum' VARCHAR(45) Null,'FlightNum' INT NULL,'OriginAirportID' INT NOT NULL,'OriginAirportSeqID' INT NOT NULL,'OriginCityMarketID' INT NOT NULL,'Origin' VARCHAR(10) NULL,'OriginCityName' VARCHAR(45) Null,'OriginState' VARCHAR(10) NULL,'OriginStateFips' INT NULL,'OriginStateName' VARCHAR(45) Null,'OriginWac' INT NOT NULL,'DestAirportID' INT NOT NULL,'DestAirportSeqID' INT NOT NULL,'DestCityMarketID' INT NOT NULL,'Dest' VARCHAR(10) NULL,'DestCityName' VARCHAR(45) Null,'DestState' VARCHAR(10) NOT NULL,'DestStateFips' INT NULL,'DestStateName' VARCHAR(45) Null,'DestWac' INT NULL,'CRSDepTime' TIME NOT NULL,'DepTime' VARCHAR(10) NULL,'DepDelay' INT NULL,'DepDelayMinutes' INT NULL,'DepDel15' INT NULL,'DepartureDelayGroups' INT NULL,'DepTimeBlk' VARCHAR(45) Null,'TaxiOut' INT NULL,'WheelsOff' VARCHAR(45) Null,'WheelsOn' VARCHAR(45) Null,'TaxiIn' INT NULL,'CRSArrTime' TIME NOT NULL,'ArrTime' VARCHAR(45) Null,'ArrDelay' INT NULL,'ArrDelayMinutes' INT NULL,'ArrDel15' INT NULL,'ArrivalDelayGroups' INT NULL,'ArrTimeBlk' VARCHAR(45) Null,'Cancelled' INT NOT NULL,'CancellationCode' VARCHAR(45) Null,'Diverted' INT NULL,'CRSElapsedTime' INT NULL,'ActualElapsedTime' INT NULL,'AirTime' INT NULL,'Flights' INT NULL,'Distance' INT NULL,'DistanceGroup' INT NULL,'CarrierDelay' INT NULL,'WeatherDelay' INT NULL,'NASDelay' INT NULL,'SecurityDelay' INT NULL,'LateAircraftDelay' INT NULL,'FirstDepTime' VARCHAR(45) Null,'TotalAddGTime' INT NULL,'LongestAddGTime' INT NULL

In [7]:
#Add the raw data to the table
#This will add from files 1 through (n-1). Since there are 12 files, we will use 1 through 13
for i in range(1,3):
    raw_path = raw_folder +'/On_Time_On_Time_Performance_2015_%s_v1.csv' %i
    create_fp_db.insert_data(db_path,raw_path,cols)
    print('Finished inserting file %s'%i)
#create_fp_db.insert_data(db_path_n,raw_path,cols)

Finished inserting file 1
Finished inserting file 2

In [4]:
#Query the DB
#Work in progress
import sqlite.tools as tools
tools.query_fp(db_path,'AA','5')

SELECT * FROM ontime_performance WHERE UniqueCarrier='AA' and DayOfWeek='5';

,YEAR,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,UniqueCarrier,AirlineID,Carrier,TailNum,...,Distance,DistanceGroup,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,FirstDepTime,TotalAddGTime,LongestAddGTime
0,2015,1,1,2,5,2015-01-02,AA,19805,AA,N795AA,...,2475,10,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
1,2015,1,1,9,5,2015-01-09,AA,19805,AA,N795AA,...,2475,10,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
2,2015,1,1,16,5,2015-01-16,AA,19805,AA,N797AA,...,2475,10,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
3,2015,1,1,23,5,2015-01-23,AA,19805,AA,N790AA,...,2475,10,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
4,2015,1,1,30,5,2015-01-30,AA,19805,AA,N792AA,...,2475,10,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
5,2015,1,1,2,5,2015-01-02,AA,19805,AA,N788AA,...,2475,10,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
6,2015,1,1,9,5,2015-01-09,AA,19805,AA,N790AA,...,2475,10,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
7,2015,1,1,16,5,2015-01-16,AA,19805,AA,N795AA,...,2475,10,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
8,2015,1,1,23,5,2015-01-23,AA,19805,AA,N792AA,...,2475,10,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
9,2015,1,1,30,5,2015-01-30,AA,19805,AA,N791AA,...,2475,10,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
10,2015,1,1,2,5,2015-01-02,AA,19805,AA,N799AA,...,2475,10,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
11,2015,1,1,9,5,2015-01-09,AA,19805,AA,N788AA,...,2475,10,0.0,0.0,18.0,0.0,0.0,None,NaN,NaN
12,2015,1,1,16,5,2015-01-16,AA,19805,AA,N799AA,...,2475,10,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
13,2015,1,1,23,5,2015-01-23,AA,19805,AA,N789AA,...,2475,10,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
14,2015,1,1,30,5,2015-01-30,AA,19805,AA,N796AA,...,2475,10,23.0,0.0,0.0,0.0,0.0,1224.0,8.0,8.0
15,2015,1,1,2,5,2015-01-02,AA,19805,AA,N796AA,...,2475,10,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
16,2015,1,1,9,5,2015-01-09,AA,19805,AA,N785AA,...,2475,10,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
17,2015,1,1,16,5,2015-01-16,AA,19805,AA,N790AA,...,2475,10,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
18,2015,1,1,23,5,2015-01-23,AA,19805,AA,N797AA,...,2475,10,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
19,2015,1,1,30,5,2015-01-30,AA,19805,AA,N786AA,...,2475,10,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
20,2015,1,1,2,5,2015-01-02,AA,19805,AA,N367AA,...,3784,11,21.0,0.0,29.0,0.0,256.0,None,NaN,NaN
21,2015,1,1,9,5,2015-01-09,AA,19805,AA,N379AA,...,3784,11,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
22,2015,1,1,16,5,2015-01-16,AA,19805,AA,N398AA,...,3784,11,23.0,0.0,0.0,0.0,0.0,None,NaN,NaN
23,2015,1,1,23,5,2015-01-23,AA,19805,AA,N381AA,...,3784,11,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
24,2015,1,1,30,5,2015-01-30,AA,19805,AA,N373AA,...,3784,11,0.0,0.0,18.0,0.0,0.0,None,NaN,NaN
25,2015,1,1,2,5,2015-01-02,AA,19805,AA,N398AA,...,3711,11,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
26,2015,1,1,9,5,2015-01-09,AA,19805,AA,N374AA,...,3711,11,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
27,2015,1,1,16,5,2015-01-16,AA,19805,AA,N352AA,...,3711,11,0.0,0.0,0.0,0.0,27.0,None,NaN,NaN
28,2015,1,1,23,5,2015-01-23,AA,19805,AA,N377AA,...,3711,11,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
29,2015,1,1,30,5,2015-01-30,AA,19805,AA,N356AA,...,3711,11,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13144,2015,1,2,20,5,2015-02-20,AA,19805,AA,N859AA,...,1235,5,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
13145,2015,1,2,27,5,2015-02-27,AA,19805,AA,N850AA,...,1235,5,0.0,0.0,29.0,0.0,3.0,None,NaN,NaN
13146,2015,1,2,6,5,2015-02-06,AA,19805,AA,N3DGAA,...,1235,5,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
13147,2015,1,2,13,5,2015-02-13,AA,19805,AA,N3ECAA,...,1235,5,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
13148,2015,1,2,20,5,2015-02-20,AA,19805,AA,N3FCAA,...,1235,5,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
13149,2015,1,2,27,5,2015-02-27,AA,19805,AA,N3FVAA,...,1235,5,0.0,67.0,92.0,0.0,0.0,None,NaN,NaN
13150,2015,1,2,6,5,2015-02-06,AA,19805,AA,N3ETAA,...,1045,5,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
13151,2015,1,2,13,5,2015-02-13,AA,19805,AA,N3ACAA,...,1045,5,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
13152,2015,1,2,20,5,2015-02-20,AA,19805,AA,N3ENAA,...,1045,5,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
13153,2015,1,2,27,5,2015-02-27,AA,19805,AA,N3GLAA,...,1045,5,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
13154,2015,1,2,6,5,2015-02-06,AA,19805,AA,N3ETAA,...,1045,5,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
13155,2015,1,2,13,5,2015-02-13,AA,19805,AA,N3ACAA,...,1045,5,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
13156,2015,1,2,20,5,2015-02-20,AA,19805,AA,N3ENAA,...,1045,5,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
13157,2015,1,2,27,5,2015-02-27,AA,19805,AA,N3GLAA,...,1045,5,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
13158,2015,1,2,6,5,2015-02-06,AA,19805,AA,N590AA,...,1345,6,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
13159,2015,1,2,13,5,2015-02-13,AA,19805,AA,N4YJAA,...,1345,6,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
13160,2015,1,2,20,5,2015-02-20,AA,19805,AA,N434AA,...,1345,6,5.0,0.0,11.0,0.0,9.0,None,NaN,NaN
13161,2015,1,2,27,5,2015-02-27,AA,19805,AA,N485AA,...,1345,6,9.0,0.0,28.0,0.0,0.0,None,NaN,NaN
13162,2015,1,2,6,5,2015-02-06,AA,19805,AA,N590AA,...,1345,6,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
13163,2015,1,2,13,5,2015-02-13,AA,19805,AA,N4YJAA,...,1345,6,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
13164,2015,1,2,20,5,2015-02-20,AA,19805,AA,N434AA,...,1345,6,7.0,0.0,0.0,0.0,14.0,None,NaN,NaN
13165,2015,1,2,27,5,2015-02-27,AA,19805,AA,N566AA,...,1345,6,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
13166,2015,1,2,6,5,2015-02-06,AA,19805,AA,N3GEAA,...,936,4,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
13167,2015,1,2,13,5,2015-02-13,AA,19805,AA,N3HAAA,...,936,4,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
13168,2015,1,2,20,5,2015-02-20,AA,19805,AA,N3FHAA,...,936,4,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
13169,2015,1,2,27,5,2015-02-27,AA,19805,AA,N3CMAA,...,936,4,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
13170,2015,1,2,6,5,2015-02-06,AA,19805,AA,N3LSAA,...,1235,5,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
13171,2015,1,2,13,5,2015-02-13,AA,19805,AA,N5DFAA,...,1235,5,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
13172,2015,1,2,20,5,2015-02-20,AA,19805,AA,N3KVAA,...,1235,5,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
13173,2015,1,2,27,5,2015-02-27,AA,19805,AA,N3EWAA,...,1235,5,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN